server:
  tomcat:
    uri-encoding: UTF-8 # 访问路径编码
    max-threads: 1000
    min-spare-threads: 30
  port: 8090 # 端口号
  connection-timeout: 5000ms
  servlet:
    context-path: /core # 访问路径的起始

spring:
  application:
    name: core-server
  profiles:
    active: dev

  # Jackson 配置项
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: true # 设置 Date 的格式，使用时间戳
      write-date-timestamps-as-nanoseconds: false # 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
      write-durations-as-timestamps: true # 设置 Duration 的格式，使用时间戳
      fail-on-empty-beans: false # 允许序列化无属性的 Bean
    deserialization:
      ACCEPT_FLOAT_AS_INT: false

  # @Cacheable 缓存配置项
  cache:
    type: REDIS
    redis:
      time-to-live: 1h # 设置过期时间为 1 小时

